language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - freddy.tandazo.yanez@alumnos.upm.es
script:
# Test
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=fatandazdba-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$apaw